export const count = state => state.count
export const filters = state => state.filters
export const list = state => state.data
export const pages = state => state.pages
export const single = state => state.single
export const current = state => state.current
export const modal = state => state.modal
export const notice = state => state.notice
export const slide = state => state.slide
